src/Entity/Goods.php
<?php

namespace App\Entity;

use DateTime;
use DateTimeInterface;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\GoodsRepository")
 */
class Goods
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $slug;

    /**
     * @ORM\Column(type="text")
     */
    private $content;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(type="datetime")
     */
    private $updated_at;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $featured_image;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="goods")
     * @ORM\JoinColumn(nullable=false)
     */
    private $users;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Commentaires", mappedBy="goods", orphanRemoval=true)
     */
    private $comments;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Keyword", inversedBy="goods")
     */
    private $keywords;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Category", inversedBy="goods")
     */
    private $categories;

    public function __construct()
    {
        $this->comments = new ArrayCollection();
        $this->keywords = new ArrayCollection();
        $this->categories = new ArrayCollection();
        $this->created_at = new DateTime();
        $this->updated_at = new DateTime();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getCreatedAt(): ?DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function getFeaturedImage(): ?string
    {
        return $this->featured_image;
    }

    public function setFeaturedImage(string $featured_image): self
    {
        $this->featured_image = $featured_image;

        return $this;
    }

    public function getUsers(): ?User
    {
        return $this->users;
    }

    public function setUsers(?User $users): self
    {
        $this->users = $users;

        return $this;
    }

    /**
     * @return Collection|Commentaires[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Commentaires $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setGoods($this);
        }

        return $this;
    }

    public function removeComment(Commentaires $comment): self
    {
        if ($this->comments->contains($comment)) {
            $this->comments->removeElement($comment);
            // set the owning side to null (unless already changed)
            if ($comment->getGoods() === $this) {
                $comment->setGoods(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Keyword[]
     */
    public function getKeywords(): Collection
    {
        return $this->keywords;
    }

    public function addKeyword(Keyword $keyword): self
    {
        if (!$this->keywords->contains($keyword)) {
            $this->keywords[] = $keyword;
        }

        return $this;
    }

    public function removeKeyword(Keyword $keyword): self
    {
        if ($this->keywords->contains($keyword)) {
            $this->keywords->removeElement($keyword);
        }

        return $this;
    }

    /**
     * @return Collection|Category[]
     */
    public function getCategories(): Collection
    {
        return $this->categories;
    }

    public function addCategory(Category $category): self
    {
        if (!$this->categories->contains($category)) {
            $this->categories[] = $category;
        }

        return $this;
    }

    public function removeCategory(Category $category): self
    {
        if ($this->categories->contains($category)) {
            $this->categories->removeElement($category);
        }

        return $this;
    }
}

src/Form/GoodsType.php
<?php

namespace App\Form;

use App\Entity\Category;
use App\Entity\Goods;
use App\Entity\User;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class GoodsType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title')
            ->add('slug')
            ->add('content')
            ->add('featured_image')
            ->add('users', EntityType::class,[
                'choice_label' => 'username',
                'class' => User::class
            ])
            ->add('keywords')
            ->add('categories', EntityType::class, [
                'choice_label' => 'label',
                'class' => Category::class
            ] )
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Goods::class,
        ]);
    }
}

src/Controller/GoodsController.php
<?php

namespace App\Controller;

use App\Entity\Commentaires;
use App\Entity\Goods;
use App\Form\CommentairesType;
use App\Form\GoodsType;
use App\Repository\GoodsRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/goods")
 */
class GoodsController extends AbstractController
{
    /**
     * @Route("/", name="goods_index", methods={"GET"})
     */
    public function index(GoodsRepository $goodsRepository): Response
    {
        return $this->render('goods/index.html.twig', [
            'goods' => $goodsRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="goods_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $good = new Goods();
        $form = $this->createForm(GoodsType::class, $good);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($good);
            $entityManager->flush();

            return $this->redirectToRoute('goods_index');
        }

        return $this->render('goods/new.html.twig', [
            'good' => $good,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="goods_show", methods={"GET"})
     */
    public function show(Goods $good): Response
    {
        return $this->render('goods/show.html.twig', [
            'good' => $good,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="goods_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Goods $good): Response
    {
        $form = $this->createForm(GoodsType::class, $good);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('goods_index');
        }

        return $this->render('goods/edit.html.twig', [
            'good' => $good,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="goods_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Goods $good): Response
    {
        if ($this->isCsrfTokenValid('delete'.$good->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($good);
            $entityManager->flush();
        }

        return $this->redirectToRoute('goods_index');
    }

    /**
     * @Route("/{slug}", name="goods_app")
     */
    public function article($slug, Request $request){
        // On récupère l'article correspondant au slug
        $article = $this->getDoctrine()->getRepository(Goods::class)->findOneBy(['slug' => $slug]);
        $commentaires = $this->getDoctrine()->getRepository(Commentaires::class)->findBy([
            'articles' => $article,
            'actif' => 1
        ],['created_at' => 'desc']);
        if(!$article){
            // Si aucun article n'est trouvé, nous créons une exception
            throw $this->createNotFoundException('L\'article n\'existe pas');
        }
        // Nous créons l'instance de "Commentaires"
        $commentaire = new Commentaires();
        // Nous créons le formulaire en utilisant "CommentairesType" et on lui passe l'instance
        $form = $this->createForm(CommentairesType::class, $commentaire);
        // Nous récupérons les données
        $form->handleRequest($request);
        // Nous vérifions si le formulaire a été soumis et si les données sont valides
        if ($form->isSubmitted() && $form->isValid()) {
            // Hydrate notre commentaire avec l'article
            $commentaire->setGoods($article);
            // Hydrate notre commentaire avec la date et l'heure courants
            $commentaire->setCreatedAt(new \DateTime('now'));
            $doctrine = $this->getDoctrine()->getManager();
            // On hydrate notre instance $commentaire
            $doctrine->persist($commentaire);
            // On écrit en base de données
            $doctrine->flush();
        }
        // Si l'article existe nous envoyons les données à la vue
        return $this->render('goods/article.html.twig', [
            'form' => $form->createView(),
            'article' => $article,
            'commentaires' => $commentaires,
        ]);
    }
}

templates/goods/_delete_form.html.twig
<form method="post" action="{{ path('goods_delete', {'id': good.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ good.id) }}">
    <button class="btn">Delete</button>
</form>

templates/goods/article.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ article.title }}{% endblock %}

{% block body %}
    <h1>{{ article.title }}</h1>
    <p>{{ article.createdAt|date }} - Commentaires : {{ commentaires|length }}</p>
    <div>{{ article.content|raw }}</div>

    <p>Catégories :
        {% for categorie in article.categories %}
            {{ categorie.nom }}
        {% endfor %}
    </p>

    <h2>Commentaires</h2>
    {% for commentaire in commentaires %}
        <p>Commentaire écrit par {{ commentaire.nickname }} le {{ commentaire.createdAt|date }}</p>
        <p>{{ commentaire.content }}</p>
    {% else %}
        <p>Il n'y a pas encore de commentaire, publiez le premier !</p>
    {% endfor %}
    {{ form(form) }}
{% endblock %}

templates/goods/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Goods{% endblock %}

{% block body %}
    <h1>Edit Goods</h1>

    {{ include('goods/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('goods_index') }}">back to list</a>

    {{ include('goods/_delete_form.html.twig') }}
{% endblock %}

templates/goods/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Goods index{% endblock %}

{% block body %}
    <h1>Goods index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Title</th>
                <th>Slug</th>
                <th>Content</th>
                <th>Created_at</th>
                <th>Updated_at</th>
                <th>Featured_image</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for good in goods %}
            <tr>
                <td>{{ good.id }}</td>
                <td>{{ good.title }}</td>
                <td>{{ good.slug }}</td>
                <td>{{ good.content }}</td>
                <td>{{ good.createdAt ? good.createdAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ good.updatedAt ? good.updatedAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ good.featuredImage }}</td>
                <td>
                    <a href="{{ path('goods_show', {'id': good.id}) }}">show</a>
                    <a href="{{ path('goods_edit', {'id': good.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="8">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('goods_new') }}">Create new</a>
{% endblock %}

templates/goods/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Goods{% endblock %}

{% block body %}
    <div class="container">
        <h1>Create new Goods</h1>

        {{ include('goods/_form.html.twig') }}

        <a href="{{ path('goods_index') }}">back to list</a>
    </div>

{% endblock %}

templates/goods/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Goods{% endblock %}

{% block body %}
    <h1>Goods</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ good.id }}</td>
            </tr>
            <tr>
                <th>Title</th>
                <td>{{ good.title }}</td>
            </tr>
            <tr>
                <th>Slug</th>
                <td>{{ good.slug }}</td>
            </tr>
            <tr>
                <th>Content</th>
                <td>{{ good.content }}</td>
            </tr>
            <tr>
                <th>Created_at</th>
                <td>{{ good.createdAt ? good.createdAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Updated_at</th>
                <td>{{ good.updatedAt ? good.updatedAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Featured_image</th>
                <td>{{ good.featuredImage }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('goods_index') }}">back to list</a>

    <a href="{{ path('goods_edit', {'id': good.id}) }}">edit</a>

    {{ include('goods/_delete_form.html.twig') }}
{% endblock %}